### PR TITLE
Fix web.xml security definitions

### PR DESCRIPTION
**Pull request by derek63**

### CODE REVIEW

**Comment by derek63** [comment]
The prior restriction of the root application context of GET only was causing SAML not to work for authenticated users (only worked correctly for lightblue-metadata-admin users).  I separated out the application and REST service proxy config so that we could allow authenticated users to GET and POST to the app (needed for SAML login sequence), but only POST/PUT/DELETE to the REST service if in the metadata admin role.

**Comment by jewzaam** [comment]
The [set default version](http://docs.lightblue.io/rest_specification/post_set_default_version_for_entity.html) API is a POST, will this allow anybody to do this?  Could the app operations security constraint's url pattern be updated to be more restrictive?

**Comment by derek63** [comment]
@jewzaam All the REST calls to lightblue from the app are proxied through the servlet defined at /rest-request, which maintains the restrictions on POST that would constrains setting default version for an entity (and other admin operations).  It is just the root context of the application that allows GET/POST for all authenticated users.

**Comment by derek63** [comment]
@alechenninger and I confirmed this is now working as expected on our deployment with SAML integration

**Pull request merged**
