### PR TITLE
Fixes #99: Using LightblueMetadataProxyServlet instead of deprecated LightblueProxyServlet

### LINKED ISSUE #99: Metadata mgmt: A trailing slash at the end of lightblue metadata endpoint breaks the app
If you configure:
    ```serviceURI=https://lightbluemetadatasvc.dev.a1.vary.redhat.com/rest/metadata/```
then metadata mgmt app will make a call like this:
    ```https://{lightblue host}/rest/metadata//termsAcknowledgement```
Which will result in:
    ```JBWEB000065: HTTP Status 404 - Could not find resource for relative : //termsAcknowledgement```

This behavior is controlled by ```com.redhat.lightblue.client.http.LightblueProxyServlet```, which is now deprecated. Use ```com.redhat.lightblue.client.http.servlet.LightblueMetadataProxyServlet``` instead for consistency with data-mgmt app and make sure it works with the trailing slash and without it. Note this will require configuration changes as well (serviceURI renamed to metadataServiceURI).

### PR DESCRIPTION
**Pull request by paterczm**
https://github.com/lightblue-platform/lightblue-applications/issues/99

Related puppet changes: https://github.com/lightblue-platform/lightblue-puppet/pull/133

### CODE REVIEW

**Comment by jewzaam** [comment]
@paterczm Could you explain why ApplicationContext was added?  I don't see it used.

**Comment by paterczm** [comment]
@jewzaam ApplicationContext is a CDI producer used to produce dependencies for the metadata servlet. See https://github.com/lightblue-platform/lightblue-client/blob/master/http/src/main/java/com/redhat/lightblue/client/http/servlet/LightblueMetadataProxyServlet.java.

**Comment by jewzaam** [comment]
@paterczm I don't see any reference to the application context.  In this PR I see a new class created but no use of that class.  Given the link you provided, would this be used by the client in a future PR?

**Comment by paterczm** [comment]
The CDI container is using ApplicationContext class. Annotations tie it all together. If I take this class away, the LightblueMetadataProxyServlet's constructor will not receive the arguments it needs.

**Comment by alechenninger** [comment]
@paterczm It certainly doesn't hurt (and you could argue it's better to be explicit), but producing a lightblue client configuration is optional. By default it will do what you put in ApplicationContext. See:

https://github.com/lightblue-platform/lightblue-client/blob/master/http/src/main/java/com/redhat/lightblue/client/http/servlet/LightblueServletContextConfiguration.java#L166

The only difference is that by default, servlet init parameters will be looked at which can override configuration. But it falls back to PropertiesLightblueClientConfiguration.fromDefault() for any that are not overridden in the web.xml.

**Comment by alechenninger** [comment]
Also see: https://github.com/lightblue-platform/lightblue-client/blob/master/http/src/test/java/com/redhat/lightblue/client/http/servlet/AbstractLightblueProxyServletTest.java#L123

**Comment by alechenninger** [comment]
Nevermind, you're using it for the http client which makes sense... sorry, nothing to see here :)

**Comment by paterczm** [comment]
@alechenninger, I'm not sure what you're proposing here - did you cancel only your 2nd post, or both?

**Comment by alechenninger** [comment]
@paterczm Sorry for confusion, ignore both. I was proposing removing the `getLightblueClientConfiguration` method but you're using that to make the http client, so it makes sense to keep it.

**Comment by dcrissman** [comment]
@paterczm if ApplicationContext is consumed by lightblue-client, then does that class belong in that library instead lightblue-application?

**Comment by paterczm** [comment]
ApplicationContext is application specific configuration of the LightblueMetadataProxyServlet. Perhaps this is more flexibility than we really need, but his is how it was designed.

**Pull request merged**
