### PR TITLE
Run Javascript unit tests in maven build (fixes #39)

### LINKED ISSUE #39: Run javascript unit tests on build
This will require interfacing with node / npm from maven. There is an active project which can do this: https://github.com/eirslett/frontend-maven-plugin

It downloads node and npm so it seems pretty portable.

Related to this is to make sure unrelated bower_components code doesn't end up in final jar. This can probably be filtered out somehow with maven configs? (Exclude everything, then only include what we need?)

### PR DESCRIPTION
**Pull request by alechenninger**
This makes mvn clean test download node, npm, then download test dependencies, then run the unit tests against the javascript code. Unit tests are placed in src/test/webapp (to mirror src/main/webapp).

Libraries used:
- Karma test runner: http://karma-runner.github.io/
- frontend-maven-plugin: https://github.com/eirslett/frontend-maven-plugin

### CODE REVIEW

**Comment by alechenninger** [comment]
Should be noted that there are unfortunately no JS unit tests... yet. But this is the infrastructure to run them within CI.

**Comment by alechenninger** [comment]
Also, as you can see the bower-downloaded dependencies are currently checked into source control. This is because bower does not yet have a version "freeze" or "shrinkwrapping" feature (https://github.com/bower/bower/issues/505) so the next best thing, though ugly, is checking dependencies into source control so the exact versions of dependencies are managed.

**Comment by luan-cestari** [comment]
Seems very nice, wasn't it possible to add the dependencies on .gitignore or something? Are you planning to add more things to this PR (maybe the tests or anything else)? Let me know so I can finish to review it and merge. Thanks =)

**Comment by luan-cestari** [comment]
Also, the repository is out sync with the master remote branch, so it would be nice to merge it.

**Comment by alechenninger** [comment]
I'll get this up to date

Unfortunately dependencies actually need to be in source control. There is an issue open to resolve this I believe

**Comment by jewzaam** [comment]
@alechenninger any chance you can get this in a state it can be merged?

**Pull request merged**
