### PR TITLE
A few metadata-mgmt app fixes

### PR DESCRIPTION
**Pull request by paterczm**
Addresses 3 issues:
* https://github.com/lightblue-platform/lightblue-applications/issues/76
* https://github.com/lightblue-platform/lightblue-applications/issues/75
* https://github.com/lightblue-platform/lightblue-applications/issues/72

Note that version sorting is done alphabetically, i.e. 0.10 will come before 0.2. It's not perfect, but hopefully sufficient.

There are no tests. See https://github.com/lightblue-platform/lightblue-applications/issues/79.

### CODE REVIEW

**Comment by dcrissman** [comment]
Is there any way I could test these changes before approving?

**Comment by dcrissman** [comment]
@paterczm you will need to merge in changes from master

**Comment by paterczm** [comment]
Openjdk7 build got stalled twice in a row. But openjdk8 passed - good enough?

**Comment by dcrissman** [comment]
@paterczm looks like this PR needs a master merge.

**Pull request merged**
