### PR TITLE
Update response for error status codes (fixes #66)

### LINKED ISSUE #66: Data Management: Display lightblue error responses in Response section
Right now errors returned from lightblue are not placed in the Response section of the page.  After discussing with @alechenninger, this is likely due to the change we made not long ago to return the correct HTTP codes that correspond to the response (instead of just returning 200 all the time).

Ideally, we should display any JSON response returned from the lightblue services, and also gracefully handle the case when the app server returns an error in HTML format (maybe strip out the HTML and wrap it in a JSON structure so the message can be displayed in the Response section).

### PR DESCRIPTION
**Pull request by alechenninger**
#66

### CODE REVIEW

**Comment by dcrissman** [comment]
Change seems simple enough. Is there anyway I could test this?

**Comment by alechenninger** [comment]
You can download the app and deploy it. There aren't many tests for this app right now. This is essential for the next release to prod, the app is kind of broken without it. I saw the versions were just bumped for this repo. Does that mean this won't get into the next release?

**Comment by dcrissman** [comment]
Thanks @alechenninger I was able to test in the way you described. Looks good, so I will merge.

**Comment by dcrissman** [comment]
The issue #66 was marked for the Bill release, so unfortunately this did not get in before Ana was cut.

**Pull request merged**
