### PR TITLE
Allow configuring data management app's lightblue hosts (environments)

### PR DESCRIPTION
**Pull request by alechenninger**
With this, the application is completely decoupled from a server side component. In the current state, all that's needed is for a consumer to download the application; the rest is just Javascript. For instance, you could even run the app by cloning the repo and serving the directory on your on machine if you had connectivity available to the lightblue hosts. It makes development on the app very fluid.

Summary of changes:
- Lightblue hosts are stored as environments in [browser side persistent local storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). Eventually this could be stored in the cloud somewhere so a user can recall their stored environments from any machine, but for now it is just browser side. There is now a management UI for adding / removing these environments, and a dropdown to select.
- The app makes AJAX reqs to lightblue directly. This requires a [CORS-enabled lightblue instance](https://github.com/lightblue-platform/lightblue-rest/issues/75), and the appropriate authentication to be done via the browser. For no auth lightblue that means it just works. For cert auth it means a user has to have a cert, and import it into their browser.
- Environment selection is done via a dropdown or the management environments UI
- No server side configuration or lightblue proxy is needed (this will affect puppet code, will open PR). Arguably the SAML auth version may no longer be needed either, but I left it in case a lightblue instance is deployed with only select allowed origins for CORS requests, in that case it _does_ matter what host the app is deployed on, and in that case it is now meaningful whether that privileged host's deployment of data management is auth'd with SAML or not.

### CODE REVIEW

**Comment by jewzaam** [comment]
Is it really necessary to include `angular-strap` in the source?  This type of thing gets out of date easily.  If it has to be bundled, couldn't we do an overlay or explode the referenced artifact as part of the build process?

**Comment by alechenninger** [comment]
The way bower works is it just clones a git repo, so there's no bundled download AFAIK. It's definitely ugly, but I was waiting on https://github.com/bower/bower/issues/505 to be fixed to stop storing deps into source control (which is not uncommon unfortunately in this case). It's nice to be able to use semantic version ranges in your bower.json dependency declarations, but these means if building downloads dependencies each time, it may get different versions on different builds, which is not really good either. Checking it into source control ensures collaborators are all using the exact same versions of dependencies.

I can look into alternative solutions until the shrinkwrap feature is implemented.

**Comment by alechenninger** [comment]
Looks like I messed up the POM... will fix this this weekend.

**Comment by jewzaam** [comment]
Moved to in progress.  Comment when it's ready for review again please @alechenninger

**Comment by alechenninger** [comment]
@jewzaam @derek63 Ready for review.

At this point there is no good solution I am aware of to avoid checking bower dependencies into source control, while still making sure that developers who check out the code base are using the same dependency versions (it is impossible to nail down transitive dependency versions due to semver version ranges). The aforementioned shrinkwrap feature that bower is working on should solve this when it is done, and if there's anything else we can do I'd like to put it off as a future refactoring.

However, to facilitate review, I removed the dependencies from this pull request. **I think though that they should be checked back in before we merge this PR however.** So please comment when review is done.

**Comment by jewzaam** [comment]
If those dependencies are required for this PR to be merged add them back in.  They can ignored for the review.

**Comment by alechenninger** [comment]
Added back -- fair warning, though, it chokes up my browser a bit looking at the review page since it is unfortunately so very large. If bower doesn't implement the shrinkwrap feature soon I might have to take a stab at it myself!! :)

**Pull request merged**
