### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by alechenninger**
Related was changing from using angular-strap to angular-ui-bootstrap which is maintained by angular team and much simpler and more angular-y to use. You can see in the code it is a lot simpler.

The first commit is only bower_components, so it can be ignored. The second commit is where I modified app to consume updated deps including the bootstrap directive usage.

### CODE REVIEW

**Comment by alechenninger** [comment]
Use this diff to review (has no bower_components in it): https://github.com/alechenninger/lightblue-applications/commit/f4cf82e5310a78e074637c71b178ba02895adbeb

**Comment by alechenninger** [comment]
Another part of the motivation of moving to ui-bootstrap is that the alert component is also easier to use that angular-strap's counterpart, and I want to use this to address #65 .

**Comment by alechenninger** [comment]
As part of the environment dropdown dependency refactor I added the `ng-cloak` directive to the dropdown. This helps address the ugliness that can happen as mentioned in #91 .

**Comment by dcrissman** [comment]
It feel like this is a more complicated PR than the subject would indicate. Should this possibly be multiple PRs?

**Comment by alechenninger** [comment]
I don't think so really. It just looks big because I changed / removed a bunch of dependencies. Updating dependencies involved finding compatible versions for everything. The original plugin for the dropdown select made that more complicated than it had to be, so I changed out that dependency for a different one. Now the dependencies are much simpler. And changing out that dependency actually only involved removing code. The only code that was added was one directive, "ng-cloak" on the dropdown.

**Comment by alechenninger** [comment]
You can see what "really" changed from this single commit: https://github.com/alechenninger/lightblue-applications/commit/f4cf82e5310a78e074637c71b178ba02895adbeb

**Comment by alechenninger** [comment]
Well, sorry, I lied a little. I had to change the index template a little bit for the new dropdown directive but, it's a very simple change, mostly rearranging what was already there.

**Comment by alechenninger** [comment]
*poke, nudge* ... is anyone looking at this? Are there any questions?

**Pull request merged**
